export const officialResources = [
  { title: 'Right to Information Act, 2005', kind: 'Act', detail: 'The principal law, available from DoPT in English, Hindi and eleven Indian languages.', href: 'https://rti.dopt.gov.in/rtiact.html', source: 'Department of Personnel & Training' },
  { title: 'Right to Information Rules, 2012', kind: 'Rules', detail: 'Central rules covering applications, fees, appeals and procedure.', href: 'https://rti.dopt.gov.in/rtiact.html', source: 'Department of Personnel & Training' },
  { title: 'RTI Act & Rules compendium', kind: 'Reference', detail: 'Consolidated official circulars, notifications, office memoranda and guidance.', href: 'https://dopt.gov.in/sites/default/files/Compendium-2023.pdf', source: 'Department of Personnel & Training' },
  { title: 'Guides and handbooks', kind: 'Guide', detail: 'Official guides for citizens, public authorities, CPIOs and appellate authorities.', href: 'https://rti.dopt.gov.in/publications.html', source: 'Department of Personnel & Training' },
  { title: 'Proactive disclosure guidance', kind: 'Section 4', detail: 'Guidelines for information public authorities should publish without waiting for an RTI.', href: 'https://rti.dopt.gov.in/publications.html', source: 'Department of Personnel & Training' },
  { title: 'Open Government Data', kind: 'Data', detail: 'Search reusable datasets, catalogues, APIs and visualisations published by government bodies.', href: 'https://data.gov.in/', source: 'Open Government Data Platform India' },
  { title: 'CIC annual reports and decisions', kind: 'Oversight', detail: 'Performance reporting, decisions, cause lists and resources from the Central Information Commission.', href: 'https://cic.gov.in/', source: 'Central Information Commission' },
  { title: 'DoPT RTI learning video', kind: 'Video', detail: 'A supplied video resource for learning about the Right to Information framework.', href: 'https://www.youtube.com/watch?v=OF--0uXYJos', source: 'YouTube · external resource' },
] as const;

export const stateCommissions = [
  ['Andhra Pradesh', 'https://sic.ap.gov.in/sic_fe/index_en.php'],
  ['Arunachal Pradesh', 'https://apic.arunachal.gov.in/'],
  ['Assam', 'https://sic.assam.gov.in/public/'],
  ['Bihar', 'https://sic.bihar.gov.in/'],
  ['Chhattisgarh', 'https://siccg.gov.in/'],
  ['Goa', 'https://www.goa.gov.in/department/goa-state-information-commission/'],
  ['Gujarat', 'http://gic.gujarat.gov.in/default.aspx'],
  ['Haryana', 'http://cicharyana.gov.in/'],
  ['Himachal Pradesh', 'http://sic.hp.gov.in/'],
  ['Jharkhand', 'http://onlinejsic.jharkhand.gov.in/'],
  ['Karnataka', 'http://www.kic.gov.in/welcome.do'],
  ['Kerala', 'https://rti.sic.kerala.gov.in/'],
  ['Madhya Pradesh', 'http://sic.mp.gov.in/'],
  ['Maharashtra', 'http://sic.maharashtra.gov.in'],
  ['Manipur', 'http://maninfocom.nic.in/'],
  ['Meghalaya', 'http://megsic.gov.in/'],
  ['Mizoram', 'https://mic.mizoram.gov.in/'],
  ['Nagaland', 'http://nlsic.nagaland.gov.in/cc.htm'],
  ['Odisha', 'https://suchana.odisha.gov.in/'],
  ['Punjab', 'http://infocommpunjab.com'],
  ['Rajasthan', 'http://ric.rajasthan.gov.in/'],
  ['Sikkim', 'https://sicsikkim.nic.in/'],
  ['Tamil Nadu', 'http://www.tnsic.gov.in/'],
  ['Telangana', 'https://tgic.telangana.gov.in/welcome.do'],
  ['Tripura', 'https://rti.tripura.gov.in/'],
  ['Uttar Pradesh', 'https://upic.gov.in/'],
  ['Uttarakhand', 'https://uic.uk.gov.in/'],
  ['West Bengal', 'https://wbic.wb.gov.in/'],
] as const;

export const glossary = [
  ['Public authority', 'A government body, institution or substantially government-financed organisation covered by the RTI Act.'],
  ['CPIO / SPIO', 'The Central or State Public Information Officer responsible for receiving and answering RTI requests.'],
  ['Section 4 disclosure', 'Information a public authority should publish proactively, so no individual request is needed.'],
  ['Section 6(3) transfer', 'Transfer of a request to another public authority when that authority holds the requested record.'],
  ['First Appellate Authority', 'The senior officer who reviews a CPIO or SPIO decision in a first appeal.'],
  ['CIC / SIC', 'The Central or State Information Commission: the independent second-appeal and complaint authority.'],
  ['BPL', 'Below Poverty Line. Eligible applicants are exempt from RTI application and information fees with valid proof.'],
  ['Life or liberty', 'The narrow urgent category in which information is due within 48 hours.'],
  ['Third party', 'A person or organisation other than the applicant and public authority whose confidential interests may be affected.'],
  ['Exemption', 'A limited statutory ground under Sections 8 or 9 for withholding information; severable non-exempt material should still be released.'],
] as const;
