export const filingGuidelines = [
  'This portal can be used by Indian citizens to file an RTI application, pay the application fee and file a first appeal online.',
  'A request may be made to Ministries, Departments and other public authorities of the Government of India.',
  'Fields marked as mandatory must be completed; all other fields are optional.',
  'The application can be written in the request-text field.',
  'Request text is limited to 3,000 characters. The current service accepts letters, numbers and these special characters: , . - _ ( ) / @ : & ? \\ %.',
  'Longer applications may be attached as a supporting PDF. Do not upload Aadhaar, PAN or another identity document, except BPL proof. The PDF filename must not contain spaces.',
  'A non-BPL applicant pays the prescribed application fee after completing the request.',
  'The current Central service accepts internet banking, Master/Visa credit or debit cards, UPI and RuPay.',
  'The application fee is prescribed by the RTI Rules, 2012.',
  'The application is submitted after payment succeeds.',
  'In the current service, if payment is debited but no registration number appears, do not pay again. Use payment reconciliation, wait 24–48 working hours, then contact the help desk with the transaction details if it remains unresolved.',
  'A citizen below the poverty line pays no application fee, but must attach valid BPL proof issued by the appropriate government.',
  'A submitted application receives a unique registration number for every future reference.',
  'The application first reaches the Nodal Officer of the selected Ministry or Department, who routes it electronically to the concerned CPIO.',
  'If the CPIO requires an additional fee for supplying the records, the notice appears in status tracking and is also sent by email or SMS.',
  'A first appeal is started from the First Appeal service and is sent to the First Appellate Authority.',
  'The original request registration number is required for a first appeal.',
  'No fee is payable for a first appeal under the Central RTI process.',
  'A mobile number may be provided to receive SMS alerts.',
  'The status of an online RTI request or first appeal can be viewed through status tracking.',
  'All requirements, time limits, exemptions and other provisions of the Right to Information Act, 2005 continue to apply.',
] as const;

export const officialFaqs = [
  ['Which public authorities can I file against here?', 'The Central portal covers Central Ministries, Departments and other Central public authorities listed in its authority directory. State and local authorities must use the appropriate State route.'],
  ['How should I write the application?', 'Ask for identifiable existing records. The form accepts up to 3,000 characters; a longer application can be attached as a supporting PDF.'],
  ['How do I pay the RTI application fee?', 'A non-BPL applicant pays the prescribed fee after completing the form. The current Central service supports internet banking, eligible cards, RuPay and UPI. A citizen with valid BPL proof is exempt.'],
  ['Will I receive proof of filing?', 'Yes. A submitted request receives a unique registration number. Keep it: it is the key for status, payments, replies and appeals.'],
  ['What happens if I select the wrong authority?', 'A Nodal Officer may transfer a Central request under section 6(3). If the receiving Central authority is not connected to the portal, the transfer can be physical. A request meant for a State authority can be returned without a fee refund.'],
  ['How will I know that an additional fee is due?', 'The CPIO records the fee notice in the case status and the portal sends an email or SMS alert. Payment is made from the same case; the citizen should not file again.'],
  ['How do I file a first appeal?', 'Use the original online request registration number and the applicant email, then state the ground and relief requested. The appeal is routed to the First Appellate Authority.'],
  ['Is there a fee for a first appeal?', 'No fee is charged for a first appeal in the Central RTI process.'],
  ['Do I need to provide a mobile number?', 'No. It is optional, but providing it enables SMS alerts. Email remains necessary for digital notices and secure status access.'],
  ['What if I forget my login details?', 'Use request history or status tracking with the filing details. A registration number should remain sufficient to recover the case through a secure privacy check.'],
  ['Must I create an account before filing?', 'No. The current Central portal allows direct filing. An account is useful only for keeping requests, payments, replies and appeals together.'],
  ['How long are cases retained online?', 'The current portal states that requests and appeals remain visible in history and status for three years. Save the acknowledgement and final reply for your own records.'],
  ['Payment was debited but no registration number appeared. What now?', 'Do not pay again. The current portal uses payment reconciliation and may take 24–48 working hours. This redesign proposes atomic payment and registration so either both succeed or neither does.'],
  ['Why can I not file a first appeal yet?', 'The portal may block an appeal when the request was physically transferred to an unconnected authority, or when no reply has arrived and the ordinary 30-day response period has not yet expired.'],
  ['Can I file an online appeal against a request filed on paper?', 'Ordinarily the current portal permits an online first appeal only against an online request. A paper request can become eligible if the CPIO lodges it in the portal and the citizen receives a registration number.'],
  ['Why is a directly filed request missing from my account history?', 'A request filed without signing in is not automatically attached to a later account. It remains available through status tracking using its registration number.'],
  ['Why did one request produce several registration numbers?', 'The Nodal Officer may split the application when several CPIOs hold different parts. Each child registration can receive its own reply and may need its own appeal.'],
  ['Where can I see the status or reply?', 'Open status tracking. It should show the current owner, transfer trail, linked registrations, fee or file requests, reply and the next available remedy.'],
  ['What if no registration number arrives after 48 working hours?', 'The current portal says unresolved payment cases are reconciled against bank records and advises the citizen to contact the bank about a refund if no number is generated. Never make repeated payments for the same request.'],
  ['How do I upload a replacement supporting document?', 'If the authority asks for a readable or additional document, open the existing case in status tracking and attach the PDF there. Do not create a new application.'],
  ['What is the RTI Online help desk for?', 'The Central help desk handles problems using the portal. It does not answer the RTI request, decide an appeal or provide records held by another public authority.'],
  ['What should I do if the browser shows a certificate warning?', 'Stop and verify the address. Do not bypass a certificate warning. A government service must maintain valid HTTPS; report the fault through an independently verified help-desk channel.'],
  ['Can I file against a State public authority here?', 'No. The Central portal is for Central public authorities. Use the correct State RTI portal or the filing route provided by the State Information Commission.'],
  ['Can a manually filed request later support an online appeal?', 'Yes, if the CPIO records the paper application in RTI Online and the citizen provided an email address or mobile number, the resulting registration number can support an online first appeal.'],
  ['Why can an RTI payment fail?', 'Common causes include disabled online-card use, a timed-out session, incorrect card or OTP details, insufficient balance, cancelling and switching payment modes, or not approving a UPI collect request in time.'],
  ['Why does status tracking use an OTP?', 'A registration number and email could expose personal request details if obtained by someone else. The OTP is a privacy check. The current portal says these OTPs remain valid until used, although delivery can be delayed.'],
] as const;
