/** States known only from source/um_citizen.pdf. Never merge with live captures. */
export const DOCUMENTED_ONLY = [
  {
    id: 'submit-request.otp',
    flow: 'submit-request',
    title: 'OTP entry after email/captcha (request)',
    previousState: 'submit-request.email-gate',
    triggeringAction: 'Correct captcha + email submit; OTP mailed/SMS',
    nextActions: ['Submit OTP → request form'],
    source: 'um_citizen.pdf p.27 (history OTP analog); live copy on email-gate says OTP is sent',
    fields: ['OTP (received in email / mobile)'],
  },
  {
    id: 'submit-request.form',
    flow: 'submit-request',
    title: 'Online RTI Request Form',
    previousState: 'submit-request.otp',
    triggeringAction: 'Valid OTP',
    nextActions: ['Select ministry/authority', 'Fill applicant details', 'BPL Yes → submit', 'BPL No → Make Payment'],
    source: 'um_citizen.pdf pp.5–8',
    fields: [
      'Search Public Authority',
      'Select Ministry/Department/Apex body *',
      'Select Public Authority *',
      'Email-ID *', 'Confirm Email-ID *', 'Name *',
      'Gender * (Male/Female/Third Gender)',
      'Address *', 'Pin code', 'Country (India/Other)', 'State',
      'Status (Rural/Urban)', 'Educational Status (Literate/Illiterate)',
      'Phone +91', 'Mobile +91 (SMS)',
      'Citizenship = Indian (locked)',
      'BPL * Yes/No',
      'Text for RTI Request application * (3000 chars, restricted charset)',
      'Supporting document PDF ≤ 1 MB',
      'Security code *',
    ],
  },
  {
    id: 'submit-request.form.bpl-yes',
    flow: 'submit-request',
    title: 'Request form — BPL branch (no ₹10, extra certificate fields)',
    previousState: 'submit-request.form',
    triggeringAction: 'BPL = Yes',
    nextActions: ['Upload BPL PDF', 'Submit (no payment)'],
    source: 'um_citizen.pdf p.6',
    fields: ['BPL Card No.', 'Year of Issue', 'Issuing Authority', 'Supporting document *', 'Submit'],
  },
  {
    id: 'submit-request.form.bpl-no',
    flow: 'submit-request',
    title: 'Request form — non-BPL (₹10, Make Payment)',
    previousState: 'submit-request.form',
    triggeringAction: 'BPL = No',
    nextActions: ['Make Payment'],
    source: 'um_citizen.pdf pp.7–8',
    fields: ['Notice: You are required to pay the RTI fee of ₹10', 'Make Payment', 'Reset'],
  },
  {
    id: 'submit-request.payment-form',
    flow: 'submit-request',
    title: 'Online Request Payment Form',
    previousState: 'submit-request.form.bpl-no',
    triggeringAction: 'Make Payment',
    nextActions: ['Select Payment Gateway radio', 'Pay', 'Back'],
    source: 'um_citizen.pdf p.9 — URL pattern /request/payment.php?requestFromid=',
    fields: ['NAME', 'RTI Fee ₹10', 'Payment Mode (Internet banking / card / RuPay / UPI)', 'Payment Gateway radio', 'Pay', 'Back'],
    notes: 'Red banner: do not refresh or register the same request again. Wait 24–48 working hours.',
  },
  {
    id: 'submit-request.sbi-gateway',
    flow: 'submit-request',
    title: 'State Bank Multi Option Payment System',
    previousState: 'submit-request.payment-form',
    triggeringAction: 'Pay',
    nextActions: ['Net banking / cards / UPI', 'CANCEL'],
    source: 'um_citizen.pdf p.10 — merchant.online-sbi.com',
    fields: ['SBI Net Banking', 'Other Banks', 'State Bank Debit Cards', 'Other Bank Debit Cards', 'Credit Cards', 'UPI', 'CANCEL'],
  },
  {
    id: 'submit-request.payment-success',
    flow: 'submit-request',
    title: 'Payment success → request registered',
    previousState: 'submit-request.sbi-gateway',
    triggeringAction: 'Successful gateway payment',
    nextActions: ['Save', 'Print', 'Print Application'],
    source: 'um_citizen.pdf pp.7, 11',
    fields: ['Registration Number', 'Name', 'Date of Filing', 'Request filed with', 'Contact Details', 'Save', 'Print', 'Print Application'],
  },
  {
    id: 'submit-request.payment-failure',
    flow: 'submit-request',
    title: 'Payment failure (reasons listed in FAQ)',
    previousState: 'submit-request.sbi-gateway',
    triggeringAction: 'Gateway decline / timeout / UPI not completed',
    nextActions: ['Payment Reconciliation', 'Do not pay again'],
    source: 'FAQ item 25 (live accordion) + guidelines point 11',
    fields: [],
  },
  {
    id: 'submit-request.payment-cancel',
    flow: 'submit-request',
    title: 'Payment cancelled on SBI gateway',
    previousState: 'submit-request.sbi-gateway',
    triggeringAction: 'CANCEL on SBI page',
    nextActions: ['Return to portal', 'Payment Reconciliation if debited'],
    source: 'um_citizen.pdf p.10 CANCEL control',
    fields: ['CANCEL'],
  },
  {
    id: 'submit-request.acknowledgement',
    flow: 'submit-request',
    title: 'Your RTI Request filed successfully',
    previousState: 'submit-request.payment-success',
    triggeringAction: 'Redirect after payment or BPL submit',
    nextActions: ['Save', 'Print', 'Print Application', 'View Status'],
    source: 'um_citizen.pdf pp.7, 11',
    fields: ['Registration Number (AAAAA/B/C/DD/EEEEE)', 'email + SMS alert'],
  },
  {
    id: 'first-appeal.form',
    flow: 'first-appeal',
    title: 'Online RTI First Appeal Form (body, after lookup)',
    previousState: 'first-appeal.lookup',
    triggeringAction: 'Valid registration number + email + captcha',
    nextActions: ['Select ground', 'Enter appeal text', 'Submit (no fee)'],
    source: 'um_citizen.pdf pp.15–16',
    fields: [
      'Ministry/Department/Apex body (pre-filled)',
      'Request Registration Number / Date (pre-filled)',
      'Appellant personal details (pre-filled)',
      'BPL',
      'Ground For Appeal * (Refused access; No response within time limit; Unreasonable fee; Incomplete/misleading/false; Any other)',
      'Text for RTI first appeal application * (manual says 500 and 3000)',
      'Supporting document PDF ≤ 1 MB',
      'Security code *',
      'Submit / Reset',
    ],
  },
  {
    id: 'first-appeal.acknowledgement',
    flow: 'first-appeal',
    title: 'Your RTI Appeal filed successfully',
    previousState: 'first-appeal.form',
    triggeringAction: 'Submit appeal (no fee)',
    nextActions: ['Save', 'Print', 'Print Application'],
    source: 'um_citizen.pdf p.17',
    fields: ['Appeal registration number', 'Name', 'Date of Filing', 'Request filed with'],
  },
  {
    id: 'view-status.otp',
    flow: 'view-status',
    title: 'OTP after status lookup',
    previousState: 'view-status.gate',
    triggeringAction: 'Valid registration + email + captcha',
    nextActions: ['Submit OTP → case card'],
    source: 'Live gate copy + um_citizen.pdf p.27 analog',
    fields: ['OTP'],
  },
  {
    id: 'view-status.case',
    flow: 'view-status',
    title: 'Case status card',
    previousState: 'view-status.otp',
    triggeringAction: 'Valid OTP',
    nextActions: ['Print RTI Application', 'Print Status', 'Go Back'],
    source: 'um_citizen.pdf p.19',
    fields: ['Registration Number', 'Name', 'Date of filing', 'Public Authority', 'Status', 'Date of action', 'Reply / Remarks', 'Nodal Officer Details'],
  },
  {
    id: 'view-status.additional-fee',
    flow: 'view-status',
    title: 'Additional payment required',
    previousState: 'view-status.case',
    triggeringAction: 'CPIO requests extra fee',
    nextActions: ['Make Payment → payment form / SBI'],
    source: 'um_citizen.pdf p.20',
    fields: ['Additional Payment amount', 'Make Payment link', 'Remarks'],
  },
  {
    id: 'view-status.upload-required',
    flow: 'view-status',
    title: 'Supporting document required from applicant',
    previousState: 'view-status.case',
    triggeringAction: 'CPIO cannot open original attachment',
    nextActions: ['Choose File', 'Attached'],
    source: 'um_citizen.pdf p.21',
    fields: ['Upload document PDF ≤ 1 MB', 'Attached'],
  },
  {
    id: 'view-status.returned-state',
    flow: 'view-status',
    title: 'Returned to applicant (State / NCT Delhi) — no refund',
    previousState: 'view-status.case',
    triggeringAction: 'Filed against a State public authority',
    nextActions: ['Go Back'],
    source: 'um_citizen.pdf p.22',
    fields: ['Status: RTI REQUEST APPLICATION RETURNED TO APPLICANT'],
  },
  {
    id: 'view-status.transferred',
    flow: 'view-status',
    title: 'Transferred to another public authority (new number)',
    previousState: 'view-status.case',
    triggeringAction: 'Section 6(3) transfer',
    nextActions: ['Open new registration number in View Status'],
    source: 'um_citizen.pdf p.23',
    fields: ['New registration number', 'Destination authority'],
  },
  {
    id: 'view-status.split-cpio',
    flow: 'view-status',
    title: 'Forwarded to multiple CPIOs (child numbers)',
    previousState: 'view-status.case',
    triggeringAction: 'Nodal officer splits the request',
    nextActions: ['Click here to view details', 'Appeal against a child number'],
    source: 'um_citizen.pdf pp.24–25',
    fields: ['Child numbers …/1 …/2 …/3', 'CPIO phone/email', 'Current status'],
  },
  {
    id: 'view-history.otp',
    flow: 'view-history',
    title: 'History OTP form',
    previousState: 'view-history.gate',
    triggeringAction: 'Valid email + mobile + captcha',
    nextActions: ['Submit OTP → dashboard'],
    source: 'um_citizen.pdf p.27',
    fields: ['OTP (Received in Email ONLY)'],
  },
  {
    id: 'view-history.dashboard',
    flow: 'view-history',
    title: 'Registered / pending / disposed counts',
    previousState: 'view-history.otp',
    triggeringAction: 'Valid OTP',
    nextActions: ['Open Registered / Pending / Disposed Requests or Appeals'],
    source: 'um_citizen.pdf p.28',
    fields: ['Requests: Registered, Disposed of, Pending', 'Appeals: Registered, Disposed of, Pending'],
  },
  {
    id: 'view-history.list',
    flow: 'view-history',
    title: 'List of Requests Registered (search + pagination)',
    previousState: 'view-history.dashboard',
    triggeringAction: 'Click Registered Requests',
    nextActions: ['Open a registration number', 'Search', 'Next page'],
    source: 'um_citizen.pdf p.29',
    fields: ['Show N entries', 'Search', 'S.No.', 'Registration Number', 'Name', 'Date of Receipt', 'Status'],
    notes: 'Number format AAAAA/B/C/DD/EEEEE documented on the same page.',
  },
  {
    id: 'login.authenticated',
    flow: 'login',
    title: 'Authenticated citizen account / drafts',
    previousState: 'login.gate',
    triggeringAction: 'Valid username + password + captcha',
    nextActions: ['History', 'Saved drafts (if any)'],
    source: 'Login form posts to validLogin.php; destination not captured live',
    fields: [],
  },
  {
    id: 'payment-reconciliation.result',
    flow: 'payment-reconciliation',
    title: 'Reconciliation result (number generated or still pending)',
    previousState: 'payment-reconciliation.gate',
    triggeringAction: 'Valid email + captcha (and likely OTP)',
    nextActions: ['Open View Status if number exists', 'Wait 24–48 working hours', 'Mail help desk'],
    source: 'FAQ item 13 + live gate; result page not captured live',
    fields: [],
  },
];
